
name: Test

on:
  workflow_dispatch:
  release:
    types: [ published ]
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/test.yml'
      - 'index.js'
      - 'conf/*'
      - 'hooks/*'



concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



jobs:
  testsshfs:
    if: ${{ !contains(github.repository, 'solaris') && !contains(github.repository, 'dragonflybsd') && !contains(github.repository, 'omnios')}}
    strategy:
      matrix:
        release: [ "6.4.0", ""]
        runs: [ "ubuntu-22.04"]
    runs-on: ${{ matrix.runs }}
    name: sshfs DragonflyBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
      SEC_VBOX : ${{ secrets.SEC_VBOX }}
      DEBUG: 1
    steps:
    - uses: actions/checkout@v4
    - name: Creating Web console
      uses: vmactions/cf-tunnel@v0
      id: tunnel
      with:
        protocol: http
        port: 8000
    - name: Test in DragonflyBSD
      id: test
      uses: vmactions/dragonflybsd-vm@28b91c567e7a25c50cadff72bb83a0734a18df5c
      with:
        envs: 'DEBUG MYTOKEN MYTOKEN2'
        prepare: |
          pkg install -y socat
        mem: 2048
        release: ${{ matrix.release }}
        nat: |
          "10022": "22"
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        sync: sshfs
        run: |
          tree .
          tree $HOME/work/
    - name: Test NAT
      run: 
        ssh -vvv -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"

  test:
    strategy:
      matrix:
        release: [ "6.4.0", ""]
        runs: [ "ubuntu-22.04"]
    runs-on: ${{ matrix.runs }}
    name: DragonflyBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
      SEC_VBOX : ${{ secrets.SEC_VBOX }}
    steps:
    - uses: actions/checkout@v4
    - name: Test in DragonflyBSD
      id: test
      uses: vmactions/dragonflybsd-vm@28b91c567e7a25c50cadff72bb83a0734a18df5c
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: |
          pkg install -y socat
        mem: 2048
        release: ${{ matrix.release }}
        nat: |
          "10022": "22"
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        run: |
          if [ -n "test" ]; then
            echo "false"
          fi
          if [ "test" ]; then
            echo "test"
          fi
          pwd
          ls -lah
          whoami
          env
          uname -a
          echo "OK"
    - name: Test NAT
      run: 
        ssh -vvv -p 10022 -i $HOME/.ssh/host.id_rsa root@localhost "uname -a;whoami;pwd"










